使用的主要数据线构是`Layer`

实现白定义层的最佳方法是扩展`tf.keras.layers.Layer`类并实现：
* `__init__`:可以在其中进行所有与输入无关的初始化，定义相关的层
* build：知道输入张量的形状并可以进行其余的初始化
* call：在这里进行前向传播

> 注意:不一定需要在build中创建变量时，也可以在`__init__`中创建它们。


tf.keras.Model和tf.keras.layers.Layer有什么区别和联系？
* 通过继承`tf.keras.Model`编写自己的模型类
* 通过继承`tf.keras.layers.Layer`编写自己的层
* `tf.keras`中的模型和层都是继承`tf.Module`实现的
* `tf.keras.Model`继承`tf.keras.layers.Layer`实现的

解释：`tf.Module`：定位为一个轻量级的状态容器，因为可以收集变量，所以这个类型可以用来建模，配合`tf.GradientTape`使用。

In [2]:
import tensorflow as tf

In [3]:
print(issubclass(tf.keras.Model,tf.Module))
print(issubclass(tf.keras.layers.Layer,tf.Module))
print(issubclass(tf.keras.Model,tf.keras.layers.Layer))

True
True
True


$y = x \cdot w +b $

假设$x \in R^{(2,2)}$, $w \in R^{(2,4)} $ , $b \in R^{(4)} $
返回 $y \in R^{(2,4)}$

下面我们实现上面的线性层

In [1]:

import tensorflow as tf
#自定义全连接层
class Linear(tf.keras.layers.Layer):

    def __init__(self, units=32, input_dim=32):
        super(Linear, self).__init__() #
        w_init = tf.random_normal_initializer()
        self.w = tf.Variable(initial_value=w_init(shape=(input_dim, units),
                                                  dtype='float32'),
                             trainable=True)
        b_init = tf.zeros_initializer()
        self.b = tf.Variable(initial_value=b_init(shape=(units,),
                                                  dtype='float32'),
                             trainable=True)

    def call(self, inputs):
        return tf.matmul(inputs, self.w) + self.b


x = tf.ones((2, 2))

linear_layer = Linear(4, 2)
y = linear_layer(x)
print(y)


tf.Tensor(
[[-0.05562585 -0.00553422  0.06386076 -0.02211853]
 [-0.05562585 -0.00553422  0.06386076 -0.02211853]], shape=(2, 4), dtype=float32)


In [2]:
linear_layer.trainable_variables

[<tf.Variable 'Variable:0' shape=(2, 4) dtype=float32, numpy=
 array([[-0.08289441, -0.00802694,  0.04252528, -0.03601141],
        [ 0.02726856,  0.00249272,  0.02133548,  0.01389288]],
       dtype=float32)>,
 <tf.Variable 'Variable:0' shape=(4,) dtype=float32, numpy=array([0., 0., 0., 0.], dtype=float32)>]

In [3]:
linear_layer.w

<tf.Variable 'Variable:0' shape=(2, 4) dtype=float32, numpy=
array([[-0.08289441, -0.00802694,  0.04252528, -0.03601141],
       [ 0.02726856,  0.00249272,  0.02133548,  0.01389288]],
      dtype=float32)>

In [4]:
linear_layer.b

<tf.Variable 'Variable:0' shape=(4,) dtype=float32, numpy=array([0., 0., 0., 0.], dtype=float32)>