In [1]:
import tensorflow as tf
print(tf.__version__)

2.3.0


In [4]:
print(tf.test.is_gpu_available())
print(tf.config.list_physical_devices('GPU'))

True
[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU'), PhysicalDevice(name='/physical_device:GPU:1', device_type='GPU'), PhysicalDevice(name='/physical_device:GPU:2', device_type='GPU'), PhysicalDevice(name='/physical_device:GPU:3', device_type='GPU'), PhysicalDevice(name='/physical_device:GPU:4', device_type='GPU'), PhysicalDevice(name='/physical_device:GPU:5', device_type='GPU'), PhysicalDevice(name='/physical_device:GPU:6', device_type='GPU'), PhysicalDevice(name='/physical_device:GPU:7', device_type='GPU')]


In [2]:
!which python

/home/zhangchunmei/anaconda3/envs/TF2/bin/python


# 一、张量
`TensorFlow` 使用一种叫 `tensor` 的数据结构去定义所有的数据，我们可以把 `tensor` 看成是 n 维的 array 或者 list。

在 `TensorFlow` 的各部分图形间流动传递的只能是tensor。

编写`TensorFlow`程序时，操纵并传递的主要对象是 `tf.Tensor`：
* 数据类型（例如 float32，int32，或string）
* 维度 shape

![](media/rank.png)

In [5]:
# Rank 0 定义0维张量
mammal = tf.Variable("Elephant", tf.string)
tf.print(tf.rank(mammal))
tf.print(tf.shape(mammal))


0
[]


In [6]:
print(tf.rank(mammal))

tf.Tensor(0, shape=(), dtype=int32)


In [7]:
# Rank 1
mystr = tf.Variable(["Hello"], tf.string)
tf.print(tf.rank(mystr))
tf.print(tf.shape(mystr))


1
[1]


In [8]:
#Rank 2
mymat=tf.Variable([[7], [11]], tf.int16)
tf.print(tf.rank(mymat))
tf.print(tf.shape(mymat))


2
[2 1]


numpy vs. tensorflow
![numpy vs. tensorflow](media/numpyvstensorflow.png)

## 创建张量

In [7]:
tf.constant([1, 2, 3], dtype=tf.int16)

<tf.Tensor: shape=(3,), dtype=int16, numpy=array([1, 2, 3], dtype=int16)>

In [8]:
tf.zeros((2, 2), dtype=tf.int16)

<tf.Tensor: shape=(2, 2), dtype=int16, numpy=
array([[0, 0],
       [0, 0]], dtype=int16)>

In [9]:
# reshape
rank_three_tensor = tf.ones([3, 4, 5])
matrix = tf.reshape(rank_three_tensor, [6, 10])

In [10]:
yet_another = tf.reshape(rank_three_tensor, [8, 10])  # 维度不对报错

SyntaxError: invalid character in identifier (<ipython-input-10-f469281ce379>, line 1)

# 二、操作

- tf.strings
- tf.debugging
- tf.dtypes
- tf.math
- tf.random
- tf.feature_column  [建议参考](https://www.tensorflow.org/tutorials/structured_data/feature_columns)，常用于特征处理.


## 01. tf.strings

In [10]:
# 字符切割
tf.strings.bytes_split('hello')

<tf.Tensor: shape=(5,), dtype=string, numpy=array([b'h', b'e', b'l', b'l', b'o'], dtype=object)>

In [11]:
help(tf.strings.split)

Help on function string_split_v2 in module tensorflow.python.ops.ragged.ragged_string_ops:

string_split_v2(input, sep=None, maxsplit=-1, name=None)
    Split elements of `input` based on `sep` into a `RaggedTensor`.
    
    Let N be the size of `input` (typically N will be the batch size). Split each
    element of `input` based on `sep` and return a `RaggedTensor` containing the 
    split tokens. Empty tokens are ignored.
    
    Example:
    
    >>> tf.strings.split('hello world').numpy()
     array([b'hello', b'world'], dtype=object)
    >>> tf.strings.split(['hello world', 'a b c'])
    <tf.RaggedTensor [[b'hello', b'world'], [b'a', b'b', b'c']]>
    
    If `sep` is given, consecutive delimiters are not grouped together and are
    deemed to delimit empty strings. For example, `input` of `"1<>2<><>3"` and
    `sep` of `"<>"` returns `["1", "2", "", "3"]`. If `sep` is None or an empty
    string, consecutive whitespace are regarded as a single separator, and the
    result wil

In [12]:
# 对空格进行切割：单词切割
tf.strings.split('hello world')

<tf.Tensor: shape=(2,), dtype=string, numpy=array([b'hello', b'world'], dtype=object)>

In [13]:
# string hash
tf.strings.to_hash_bucket(['hello','world'], num_buckets=10)

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([8, 1])>

## 02. tf.debugging

In [14]:
# tf自带debug函数 (x 是否等于 y)
a = tf.random.uniform((10, 10))
tf.debugging.assert_equal(x=a.shape, y=(10,10))

In [15]:
# 错误示范
tf.debugging.assert_equal(x=a.shape, y=(20,10))

InvalidArgumentError: Condition x == y did not hold.
Indices of first 1 different values:
[[0]]
Corresponding x values:
[10]
Corresponding y values:
[20]
First 2 elements of x:
[10 10]
First 2 elements of y:
[20 10]

## 03. tf.random

In [16]:
a = tf.random.uniform(shape=(10, 5), minval=0, maxval=10)
a

<tf.Tensor: shape=(10, 5), dtype=float32, numpy=
array([[4.3930521e+00, 9.9396887e+00, 5.0853004e+00, 5.8937335e+00,
        8.1611843e+00],
       [2.5842655e+00, 4.0587521e+00, 4.9796653e+00, 9.4833956e+00,
        2.8490758e+00],
       [6.6873908e+00, 1.5095270e+00, 9.9422874e+00, 5.7644167e+00,
        1.4041543e-01],
       [6.5287066e+00, 2.5718594e+00, 9.2470884e+00, 9.1433830e+00,
        8.3603477e+00],
       [5.4355583e+00, 9.0309372e+00, 4.9365830e+00, 1.4705503e+00,
        1.2285590e-01],
       [6.0117245e-03, 4.8105121e-01, 6.0948968e+00, 3.4438109e+00,
        8.8326473e+00],
       [2.6749790e+00, 8.5772705e+00, 1.7811382e+00, 2.1951151e+00,
        3.8591957e+00],
       [6.2491035e+00, 6.6134205e+00, 5.9531665e+00, 6.2340808e+00,
        1.3564539e+00],
       [8.7575531e+00, 7.9608798e+00, 2.3329306e+00, 9.6564398e+00,
        9.5569668e+00],
       [5.9340944e+00, 2.4035919e+00, 3.7998617e+00, 6.9467807e+00,
        1.7403567e+00]], dtype=float32)>

## 04. tf.math

In [17]:
a = tf.constant([[1, 2], [3, 4]])
b = tf.constant([[5, 6], [7, 8]])

tf.print(tf.math.add(a, b))
tf.print(tf.math.subtract(a, b))
tf.print(tf.math.multiply(a, b))
tf.print(tf.math.divide(a, b))

[[6 8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[5 12]
 [21 32]]
[[0.2 0.33333333333333331]
 [0.42857142857142855 0.5]]


In [19]:
print(tf.math.add(a, b))

tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)


tf.print:输出张量里头的内容；
print:输出的是张量，

## 05. tf.dtypes

In [18]:
x = tf.constant([1.8, 2.2], dtype=tf.float32)

x1 = tf.dtypes.cast(x, tf.int32)  # float32 -> int32
x1

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

# 三、常用层

- `tf.keras.layers`
- `tf.nn`

在大多数据情况下，可以使用 `TensorFlow` 封装的 `tf.keras.layers` 构建的一些层建模，Keras层是非常有用的。

可以在[文档中](https://www.tensorflow.org/api_docs/python/tf/keras/layers)查看预先存在的层的完整列表。它包括Dense，Conv2D，LSTM，BatchNormalization，Dropout等。

In [21]:
# 文本分类

a = tf.random.uniform(shape=(10, 100, 50), minval=-0.5, maxval=0.5)  # 张量

x = tf.keras.layers.LSTM(100)(a)  # LSTM

x = tf.keras.layers.Dense(10)(x)  # 全连接层

x = tf.nn.softmax(x)  # 激活函数

增加层的参数配置

In [22]:
# 层中增加激活函数
tf.keras.layers.Dense(64, activation='relu')
# or
tf.keras.layers.Dense(64, activation=tf.nn.relu)


# 将L1正则化系数为0.01的线性层应用于内核矩阵
tf.keras.layers.Dense(64, kernel_regularizer=tf.keras.regularizers.l1(0.01))

# 将L2正则化系数为0.01的线性层应用于偏差向量：
tf.keras.layers.Dense(64, bias_regularizer=tf.keras.regularizers.l2(0.01))

# 内核初始化为随机正交矩阵的线性层：
tf.keras.layers.Dense(64, kernel_initializer='orthogonal')

# 偏差向量初始化为2.0的线性层：
tf.keras.layers.Dense(64, bias_initializer=tf.keras.initializers.Constant(2.0))

`tf.nn`:底层的函数库，其他各种库可以说都是基于这个底层库来进行扩招

`tf.keras.layers`:如果说`tf.nn`是轮子，那么`tf.keras.layers`可以说是汽车。`tf.keras.layers`是基于`tf.nn`的高度封装。


推荐tensorflow的资源:
* https://zh.d2l.ai/
* https://www.tensorflow.org/api/r2.0
* https://tf.wiki/zh_hans/
* https://lyhue1991.github.io/eat_tensorflow2_in_30_days/
